sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hawful70/docker-react-test -f Dockerfile.dev .
script:
  - docker run -e CI=true hawful70/docker-react-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'docker-react-test'
  env: 'DockerReactTest-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-456356320920'
  bucket_path: 'docker-react-test'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
